"use client";

import { useState } from "react";
import { Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { toast } from "sonner";
import { generateInsights } from "./insights-actions";

export function InsightsCard() {
  const [loading, setLoading] = useState(false);
  const [insights, setInsights] = useState<string | null>(null);

  async function handleGenerate() {
    setLoading(true);
    try {
      const result = await generateInsights();
      if (result.error) {
        toast.error(result.error);
      } else {
        setInsights(result.insights);
      }
    } catch {
      toast.error("Failed to generate insights");
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="rounded-lg border border-border bg-card p-4">
      <div className="flex items-center justify-between mb-3">
        <h3 className="text-sm font-medium flex items-center gap-2">
          <Sparkles className="size-4 text-primary" />
          AI Insights
        </h3>
        <Button
          size="sm"
          variant="secondary"
          className="gap-1.5"
          onClick={handleGenerate}
          disabled={loading}
        >
          <Sparkles className="size-3.5" />
          {loading ? "Generating…" : insights ? "Regenerate" : "Generate AI Insights"}
        </Button>
      </div>

      {insights ? (
        <div className="rounded-md border border-primary/20 bg-primary/5 p-4 text-sm leading-relaxed">
          <div className="prose prose-sm prose-invert max-w-none">
            {insights.split("\n").map((line, i) => {
              const trimmed = line.trim();
              if (!trimmed) return null;
              if (trimmed.startsWith("- ")) {
                return (
                  <div key={i} className="flex gap-2 mb-1.5">
                    <span className="text-primary mt-0.5 shrink-0">•</span>
                    <span>{trimmed.slice(2)}</span>
                  </div>
                );
              }
              return (
                <p key={i} className="mb-1.5">
                  {trimmed}
                </p>
              );
            })}
          </div>
          <p className="text-[10px] text-muted-foreground mt-3 flex items-center gap-1">
            <Sparkles className="size-3" />
            Generated by AI — verify numbers against the report table above.
          </p>
        </div>
      ) : !loading ? (
        <p className="text-sm text-muted-foreground">
          Click &ldquo;Generate AI Insights&rdquo; to get AI-powered analysis of
          your fleet data.
        </p>
      ) : (
        <div className="space-y-2 animate-pulse">
          <div className="h-4 bg-secondary rounded w-3/4" />
          <div className="h-4 bg-secondary rounded w-5/6" />
          <div className="h-4 bg-secondary rounded w-2/3" />
        </div>
      )}
    </div>
  );
}
